name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  # Ubuntu tests
  Ubuntu_testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs tests
      - name: Tests
        run: python3 -m unittest tests.py

  # Windows tests
  Windows_testing:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Runs tests
      - name: Tests
        run: python3.exe -m unittest tests.py
